const mongoose = require('mongoose');
const path = require('path');
const NGO = require('./models/NGO');
const User = require('./models/User');
require('dotenv').config({ path: path.join(__dirname, '.env') });

const seedNGOs = async () => {
  try {
    const MONGODB_URI = process.env.MONGODB_URI || 'mongodb://127.0.0.1:27017/seva-connect-hub';
    await mongoose.connect(MONGODB_URI);
    console.log('Connected to MongoDB for NGO seeding...');

    // 1. Clear existing NGO data (optional but cleaner for testing)
    await NGO.deleteMany({});
    console.log('Cleared existing NGOs.');

    // 2. Find or create a dummy owner user
    let owner = await User.findOne({ email: 'ngo_owner_test@example.com' });
    if (!owner) {
      owner = await User.create({
        name: 'NGO Test Owner',
        email: 'ngo_owner_test@example.com',
        password: 'password123',
        role: 'ngo',
        phone: '+91 99887 76655',
        description: 'Testing account for NGOs'
      });
      console.log('Created dummy NGO owner user.');
    }

    const dummyNGOs = [
      {
        ngoName: 'Tamil Culture Foundation',
        description: 'Dedicated to preserving and promoting the rich cultural heritage, literature, and arts of Tamil Nadu through community workshops and exhibitions.',
        mission: 'To ensure the immortality of Tamil traditions in the modern world.',
        category: 'arts',
        email: 'arts1@example.com',
        phone: '+91 44 2345 6789',
        address: '12, Marina Beach Road, Mylapore',
        city: 'Chennai',
        ownerId: owner._id,
        registrationCompleted: true,
        status: 'approved',
        image: '/assets/tamilculture.jpeg',
        areasOfOperation: ['Chennai', 'Kanchipuram'],
        yearEstablished: 1995,
        services: ['Tamil Classes', 'Folk Art Training', 'Cultural Festivals'],
      },
      {
        ngoName: 'Salem Health Mission',
        description: 'Providing comprehensive mobile medical clinics and health awareness programs in rural Salem districts.',
        mission: 'Quality healthcare for every remote village in Salem.',
        category: 'health',
        email: 'health@salem.org',
        phone: '+91 427 123 4567',
        address: '55, Steel Plant Road, Salem',
        city: 'Salem',
        ownerId: owner._id,
        registrationCompleted: true,
        status: 'approved',
        image: '/assets/health.webp',
        areasOfOperation: ['Salem', 'Omalur'],
        yearEstablished: 2005,
        services: ['Mobile Clinics', 'Vaccination Drives', 'Nutrition Aid'],
      },
      {
        ngoName: 'Coimbatore Women Rise',
        description: 'Empowering women in the textile capital through skill development, vocational training, and legal literacy programs.',
        mission: 'Building self-reliant women for a stronger Kovai.',
        category: 'women',
        email: 'women@kovai.org',
        phone: '+91 422 555 8888',
        address: 'Cotton Mills Colony, Peelamedu',
        city: 'Coimbatore',
        ownerId: owner._id,
        registrationCompleted: true,
        status: 'approved',
        image: '/assets/women empowerment.jpg',
        areasOfOperation: ['Coimbatore', 'Tiruppur'],
        yearEstablished: 2010,
        services: ['Skill Training', 'Microfinance', 'Legal Aid'],
      },
      {
        ngoName: 'Kovai Green Hands',
        description: 'Environmental initiative for large-scale afforestation and urban gardening in the industrial belt of Coimbatore.',
        category: 'environment',
        email: 'green@kovai.org',
        phone: '+91 422 987 6543',
        address: '88, RS Puram, West Link Road',
        city: 'Coimbatore',
        ownerId: owner._id,
        registrationCompleted: true,
        status: 'approved',
        image: '/assets/greenhands.webp', // environment -> green hands image
        areasOfOperation: ['Coimbatore', 'Pollachi'],
        yearEstablished: 2008,
      },
      {
        ngoName: 'Erode Inclusive Trust',
        description: 'Promoting accessibility and inclusion for people with disabilities through adaptive sports and vocational placement.',
        mission: 'Disability is not a barrier to excellence.',
        category: 'disability',
        email: 'able@erode.org',
        phone: '+91 424 555 4444',
        address: '10, Gobi Road, Modakkurichi',
        city: 'Erode',
        ownerId: owner._id,
        registrationCompleted: true,
        status: 'approved',
        image: '/assets/Support-to-differently-Abled-bnr.jpg',
        areasOfOperation: ['Erode', 'Namakkal'],
        yearEstablished: 2014,
        services: ['Physiotherapy', 'Job Placement', 'Sign Language Classes'],
      },
      {
        ngoName: 'Chennai Golden Age Home',
        description: 'Providing a dignifies life and medical support for senior citizens who have been abandoned or need professional care.',
        mission: 'Love and respect for our elders.',
        category: 'elderly',
        email: 'eldery@chennai.org',
        phone: '+91 44 8888 2222',
        address: 'Besant Nagar Senior Living Hub',
        city: 'Chennai',
        ownerId: owner._id,
        registrationCompleted: true,
        status: 'approved',
        image: '/assets/eldery.webp',
        areasOfOperation: ['Chennai'],
        yearEstablished: 2002,
        services: ['Residential Care', 'Palliative Care', 'Social Events'],
      },
      {
        ngoName: 'Madurai Paws & Protection',
        description: 'Dedicated to the rescue, sterilization, and care of abandoned animals in the temple city region.',
        mission: 'A voice for the voiceless cats and dogs of Madurai.',
        category: 'animals',
        email: 'paws@madurai.org',
        phone: '+91 91234 11223',
        address: 'Subramaniapuram Pet Zone',
        city: 'Madurai',
        ownerId: owner._id,
        registrationCompleted: true,
        status: 'approved',
        image: '/assets/animals.jpg',
        areasOfOperation: ['Madurai', 'Theni'],
        yearEstablished: 2016,
        services: ['Animal SOS', 'Foster Care', 'Bird Rescue'],
      },
      {
        ngoName: 'Delta Farmers Union',
        description: 'Supporting delta region farmers with modern tech-integrated sustainable agricultural practices and better market linkages.',
        category: 'agriculture',
        email: 'delta@farmers.org',
        phone: '+91 4362 778899',
        address: '15, Medical College Road, Thanjavur',
        city: 'Thanjavur',
        ownerId: owner._id,
        registrationCompleted: true,
        status: 'approved',
        image: '/assets/agriculture.jpeg',
        areasOfOperation: ['Thanjavur', 'Kumbakonam'],
        yearEstablished: 1985,
        services: ['Agri Training', 'Seed Banks', 'Fair Price Market'],
      },
      {
        ngoName: 'Coastal Response India',
        description: 'Equipping coastal communities of Tamil Nadu with disaster preparedness and rapid response medical aid.',
        mission: 'Resilience for the coastal heartland.',
        category: 'disaster',
        email: 'disaster@coastal.org',
        phone: '+91 4142 990011',
        address: 'Cuddalore Beach Front Road',
        city: 'Cuddalore',
        ownerId: owner._id,
        registrationCompleted: true,
        status: 'approved',
        image: '/assets/coastal.jpeg',
        areasOfOperation: ['Cuddalore', 'Pondicherry', 'Nagapattinam'],
        yearEstablished: 2004,
        services: ['Rescue Ops', 'Shelter Camps', 'Relief Kits'],
      },
      {
        ngoName: 'Cauvery Water Save',
        description: 'Grassroots organization for sustainable water usage in the Cauvery basin for farmers and residential areas.',
        category: 'environment',
        email: 'water@savetamil.org',
        phone: '+91 431 333 4444',
        address: 'Srirangam River Complex',
        city: 'Tiruchirappalli',
        ownerId: owner._id,
        registrationCompleted: true,
        image: '/assets/coastal.jpeg',
        areasOfOperation: ['Tiruchirappalli', 'Karur'],
      },
      {
        ngoName: 'Nilgiris Tribal Schools',
        description: 'Educational programs for tribal children in the Ooty and Nilgiris district, focused on quality basic education.',
        category: 'education',
        email: 'tribal@ootyedu.org',
        phone: '+91 423 777 6666',
        address: 'Lower Coonoor Road, Ooty',
        city: 'Udagamandalam',
        ownerId: owner._id,
        registrationCompleted: true,
        status: 'approved',
        image: '/assets/education2.jpeg',
        areasOfOperation: ['Ooty', 'Gudalur'],
        yearEstablished: 1999,
        services: ['Residential Schools', 'Vocational Training'],
      },
      {
        ngoName: 'Madurai Education Trust',
        description: 'Empowering students in Madurai through scholarships and study material support.',
        category: 'education',
        email: 'help@maduraiedu.org',
        phone: '+91 452 111 2222',
        city: 'Madurai',
        ownerId: owner._id,
        registrationCompleted: true,
        status: 'approved',
        image: '/assets/education3.jpg',
        areasOfOperation: ['Madurai'],
      },
      {
        ngoName: 'Salem Weavers Guild',
        description: 'Reviving traditional handloom techniques by supporting local weavers in Salem.',
        category: 'arts',
        email: 'weavers@salem.org',
        phone: '+91 427 444 3333',
        city: 'Salem',
        ownerId: owner._id,
        registrationCompleted: true,
        status: 'approved',
        image: '/assets/Weaver3.jpg',
        areasOfOperation: ['Salem'],
      },
      {
        ngoName: 'Farmers Support Group',
        category: 'agriculture',
        email: 'farmers@erode.org',
        city: 'Erode',
        ownerId: owner._id,
        registrationCompleted: true,
        image: '/assets/agriculture.jpeg',
        rejectionReason: 'The provided documents are not valid for the current fiscal year.',
      },
      {
        ngoName: 'Chennai Kids Care',
        category: 'children',
        email: 'kids@chennai.org',
        city: 'Chennai',
        ownerId: owner._id,
        registrationCompleted: true,
        status: 'approved',
        image: '/assets/kids.jpeg',
        areasOfOperation: ['Chennai'],
      },
      {
        ngoName: 'Kanyakumari Marine Life',
        category: 'environment',
        email: 'marine@kanyakumari.org',
        city: 'Kanyakumari',
        ownerId: owner._id,
        registrationCompleted: true,
        status: 'approved',
        image: '/assets/marine.jpg',
        areasOfOperation: ['Kanyakumari'],
      },
      {
        ngoName: 'Madurai Medical Aid',
        category: 'health',
        email: 'medic@madurai.org',
        city: 'Madurai',
        ownerId: owner._id,
        registrationCompleted: true,
        status: 'approved',
        image: '/assets/medical aid.avif',
        areasOfOperation: ['Madurai'],
      },
      {
        ngoName: 'Trichy Able Hands',
        category: 'disability',
        email: 'able@trichy.org',
        city: 'Tiruchirappalli',
        ownerId: owner._id,
        registrationCompleted: true,
        status: 'approved',
        image: '/assets/disability2.webp',
        areasOfOperation: ['Tiruchirappalli'],
      },
      {
        ngoName: 'Salem Silver Lining',
        category: 'elderly',
        email: 'silver@salem.org',
        city: 'Salem',
        ownerId: owner._id,
        registrationCompleted: true,
        status: 'approved',
        image: '/assets/eldery.webp',
        areasOfOperation: ['Salem'],
      },
      {
        ngoName: 'Chennai Shakti Support',
        category: 'women',
        email: 'shakti@chennai.org',
        city: 'Chennai',
        ownerId: owner._id,
        registrationCompleted: true,
        status: 'approved',
        image: '/assets/Women-Empowerment-Banner-700x228.jpg',
        areasOfOperation: ['Chennai'],
      },
      {
        ngoName: 'Thanjavur Arts Revival',
        category: 'arts',
        email: 'thanjavur@arts.org',
        city: 'Thanjavur',
        ownerId: owner._id,
        registrationCompleted: true,
        status: 'approved',
        image: '/assets/art.avif',
        areasOfOperation: ['Thanjavur'],
      },
      {
        ngoName: 'Namakkal Poultry Welfare',
        category: 'animals',
        email: 'poultry@namakkal.org',
        city: 'Namakkal',
        ownerId: owner._id,
        registrationCompleted: true,
        status: 'approved',
        image: '/assets/animals.jpg',
        areasOfOperation: ['Namakkal'],
      },
      {
        ngoName: 'Tiruppur Labor Education',
        category: 'education',
        email: 'labor@tiruppur.org',
        city: 'Tiruppur',
        ownerId: owner._id,
        registrationCompleted: true,
        status: 'approved',
        image: '/assets/child.jpg',
        areasOfOperation: ['Tiruppur'],
      },
      {
        ngoName: 'Pollachi Organic Net',
        category: 'agriculture',
        email: 'organic@pollachi.org',
        city: 'Coimbatore',
        ownerId: owner._id,
        registrationCompleted: true,
        status: 'approved',
        image: '/assets/agriculture2.jpeg',
        areasOfOperation: ['Coimbatore', 'Pollachi'],
      },
      {
        ngoName: 'Dindigul Care Home',
        category: 'elderly',
        email: 'care@dindigul.org',
        city: 'Dindigul',
        ownerId: owner._id,
        registrationCompleted: true,
        status: 'approved',
        image: '/assets/eldery2.webp',
        areasOfOperation: ['Dindigul'],
      }
    ];

    await NGO.insertMany(dummyNGOs);
    console.log(`Successfully seeded ${dummyNGOs.length} NGOs.`);

    mongoose.disconnect();
    console.log('Seed completed.');
  } catch (error) {
    console.error('Error seeding NGOs:', error);
    process.exit(1);
  }
};

seedNGOs();
